server:
  port: 7777
spring:
  application:
    name: blog-view
    # dev test, prod
    profiles:
      active: dev
  security:
    user:
      name: user
      password: 123
  datasource:
    url: jdbc:mysql://localhost:3306/xupt_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

#  # 返回json的全局时间格式
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8


mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  # * 不可以少，少了通配符 不起作用
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      #如果java实体类没加注解@TableLogic，则可以配置这个，推荐这里配置
      logic-delete-field: del_flag # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为0)
      # 若逻辑已删除和未删除的值和默认值一样，则可以不配置这2项
      # 主键自增策略
      id-type: auto
      table-prefix: blog_
      map-underscore-to-camel-case: true #自动驼峰映射
